/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tgif.apps;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mon
 */
public class GridLayoutTest extends javax.swing.JFrame {

    public static Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();

    /**
     * Creates new form GridLayout
     */
    public GridLayoutTest() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        gridLayout();
    }
    private JLabel[] tableNum;
    private JPanel[] tables;
    private JLabel[] status;
    private int i;
    private int tableCount = 25;

    private void gridLayout() {

        Color color[] = new Color[]{
            Color.yellow, Color.green, Color.blue,
            Color.pink, Color.red, Color.DARK_GRAY,
            Color.DARK_GRAY, Color.DARK_GRAY, Color.DARK_GRAY,
            Color.DARK_GRAY, Color.DARK_GRAY, Color.DARK_GRAY, Color.DARK_GRAY,
            Color.DARK_GRAY, Color.DARK_GRAY, Color.DARK_GRAY, Color.DARK_GRAY,
            Color.DARK_GRAY, Color.DARK_GRAY, Color.DARK_GRAY, Color.DARK_GRAY,
            Color.DARK_GRAY, Color.DARK_GRAY, Color.DARK_GRAY, Color.DARK_GRAY
        };
        tableNum = new JLabel[tableCount];
        tables = new JPanel[tableCount];
        status = new JLabel[tableCount];
        GridLayout gLayout;
        if (tableCount == 1) {
            gLayout = new GridLayout(0, 1);
            gLayout.setHgap(5);
            gLayout.setVgap(5);
            jPanel1.setLayout(gLayout);
        } else if (tableCount < 11) {
            if ((tableCount % 2) == 0) {
                gLayout = new GridLayout(2, 3);
                gLayout.setHgap(5);
                gLayout.setVgap(5);
                jPanel1.setLayout(gLayout);
            } else if ((tableCount % 1) == 0) {
                gLayout = new GridLayout(3, 3);
                gLayout.setHgap(5);
                gLayout.setVgap(5);
                jPanel1.setLayout(gLayout);
            }
        } else if (tableCount > 10) {
            if ((tableCount % 2) == 0) {
                System.out.println("here1");
                gLayout = new GridLayout(4, 4);
                gLayout.setHgap(5);
                gLayout.setVgap(5);
                jPanel1.setLayout(gLayout);

            } else if ((tableCount % 1) == 0) {
                System.out.println("here");
                gLayout = new GridLayout(5, 5);
                gLayout.setHgap(5);
                gLayout.setVgap(5);
                jPanel1.setLayout(gLayout);

            }
        } else {
            System.out.println("error");
        }

        jPanel1.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        for (i = 0; i < tableCount; i++) {
            tables[i] = new JPanel();
            tables[i].setLayout(new BoxLayout(tables[i], BoxLayout.Y_AXIS));
            jPanel1.add(tables[i]);
            tables[i].setBackground(color[i]);
            tables[i].setName("#" + (i + 1));

            tables[i].addMouseListener(new MouseAdapter() {
                private int myIndex;
                // inner class

                {
                    this.myIndex = i;
                }

                @Override
                public void mouseClicked(MouseEvent me) {
                    super.mouseClicked(me); //To change body of generated methods, choose Tools | Templates.
                    JOptionPane.showMessageDialog(null, tables[myIndex].getName());
                }
            });

            tableNum[i] = new JLabel();
            tableNum[i].setFont(new Font("Tahoma", Font.PLAIN, 24));
            tableNum[i].setText("#" + (i + 1));
            tableNum[i].setAlignmentX(Component.CENTER_ALIGNMENT);

            status[i] = new JLabel();
            status[i].setFont(new Font("Tahoma", Font.PLAIN, 24));
            status[i].setText("Waiting");
            status[i].setAlignmentX(Component.CENTER_ALIGNMENT);
            
//            tables[i].add(Box.createHorizontalBox());
            tables[i].add(tableNum[i]);
            tables[i].add(Box.createRigidArea(new Dimension(0, 30)));
            tables[i].add(status[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GridLayoutTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GridLayoutTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GridLayoutTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GridLayoutTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GridLayoutTest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
