/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tgif.view;

import com.tgif.dao.FoodItemsDao;
import com.tgif.model.FoodItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Mon
 */
public class FormPromo extends javax.swing.JDialog {

    FoodItem foodItem;

    public void setFoodItem(FoodItem foodItem) {
        this.foodItem = foodItem;
    }

    /**
     * Creates new form FormFoodItem
     */
    public FormPromo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        jTextFieldItemId.setVisible(false);
    }

    public void setData() {
        if (this.foodItem != null) {
            if (this.foodItem.getPromoStatus().equalsIgnoreCase("A")) {
                jTextFieldItemId.setText(String.valueOf(this.foodItem.getItemId()));
                jTextFieldName.setText(this.foodItem.getItemName());
                jTextFieldPromoPrice.setText(String.valueOf(this.foodItem.getPromoPrice()));
                jRadioButtonActive.setSelected(true);
            } else {
                jTextFieldItemId.setText(String.valueOf(this.foodItem.getItemId()));
                jTextFieldName.setText(this.foodItem.getItemName());
                jRadioButtonInactive.setSelected(true);
            }
        }
        if (jRadioButtonInactive.isSelected()) {
            jTextFieldPromoPrice.setEnabled(false);
            jTextFieldPromoPrice.setText("0.00");
            jButtonSave.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldItemId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPromoPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRadioButtonActive = new javax.swing.JRadioButton();
        jRadioButtonInactive = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 23));

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldName.setEnabled(false);
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 270, 30));

        jButtonSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 80, 30));

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 80, 30));
        jPanel1.add(jTextFieldItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Promo Price:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 23));

        jTextFieldPromoPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextFieldPromoPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 270, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Promo Status:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 23));

        buttonGroup1.add(jRadioButtonActive);
        jRadioButtonActive.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonActive.setText("Active");
        jRadioButtonActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActiveActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, -1));

        buttonGroup1.add(jRadioButtonInactive);
        jRadioButtonInactive.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonInactive.setText("Inactive");
        jRadioButtonInactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonInactiveActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonInactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 80, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 270, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            if (Integer.valueOf(jTextFieldPromoPrice.getText().trim()) < 0) {
                JOptionPane.showMessageDialog(this, "You inserted negative number");
                jTextFieldPromoPrice.requestFocus();
                jTextFieldPromoPrice.selectAll();
                return;
            }
            JOptionPane.showMessageDialog(this, "success");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Not a number");
            jTextFieldPromoPrice.requestFocus();
            jTextFieldPromoPrice.selectAll();
        }

//        if(Integer.valueOf(jTextFieldPromoPrice.getText().trim()) < 0) {
//            JOptionPane.showMessageDialog(this, "Not a number or less than 0");
//            return;
//        }
        FoodItemsDao foodItemsDao = new FoodItemsDao();
        FoodItem localFoodItem = new FoodItem();
        localFoodItem.setItemId(Integer.valueOf(jTextFieldItemId.getText()));
        localFoodItem.setPromoPrice(Double.valueOf(jTextFieldPromoPrice.getText()));
        String status = jRadioButtonActive.isSelected() ? "A" : "I";
        localFoodItem.setPromoStatus(status);
        foodItemsDao.addEditPromo(localFoodItem);
        this.dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jRadioButtonInactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonInactiveActionPerformed
        jRadioButtonInactive.setSelected(true);
        jTextFieldPromoPrice.setText("0.00");
        jTextFieldPromoPrice.setEnabled(false);
        jButtonSave.requestFocus();
    }//GEN-LAST:event_jRadioButtonInactiveActionPerformed

    private void jRadioButtonActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonActiveActionPerformed
        jRadioButtonActive.setSelected(true);
        jTextFieldPromoPrice.setEnabled(true);
        jTextFieldPromoPrice.selectAll();
        jTextFieldPromoPrice.requestFocus();
    }//GEN-LAST:event_jRadioButtonActiveActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonActive;
    private javax.swing.JRadioButton jRadioButtonInactive;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldItemId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPromoPrice;
    // End of variables declaration//GEN-END:variables
}
