/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tgif.view;

import com.tgif.dao.CategoryDao;
import com.tgif.dao.FoodItemsDao;
import com.tgif.model.Category;
import com.tgif.model.FoodItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Mon
 */
public class FormFoodItem extends javax.swing.JDialog {
    
    private FoodItem foodItem;
    private String formAction = "edit";

    public void setFoodItem(FoodItem foodItem) {
        this.foodItem = foodItem;
    }
    /**
     * Creates new form FormFoodItem
     */
    public FormFoodItem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextFieldItemId.setVisible(false);
        jComboBoxCategoryId.setVisible(false);
        getCategory();
    }
    
    public void setData() {
        if (this.foodItem != null) {
            jTextFieldItemId.setText(String.valueOf(this.foodItem.getItemId()));
            jTextFieldName.setText(this.foodItem.getItemName());
            jComboBoxCategory.setSelectedItem(this.foodItem.getCategory().getName());
            jTextField2.setText(this.foodItem.getImage());
            jTextAreaDescription.setText(this.foodItem.getDescription());
            this.formAction = "edit";
        } else {
            System.out.println("null");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jComboBoxCategoryId = new javax.swing.JComboBox();
        jTextFieldItemId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 23));

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Category:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 23));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 380, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Image:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, 23));

        jComboBoxCategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Category" }));
        jComboBoxCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCategoryItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 380, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Description:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, 23));

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextAreaDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 380, 140));

        jButtonSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 80, 30));

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 80, 30));

        jComboBoxCategoryId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Category Id" }));
        jPanel1.add(jComboBoxCategoryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 320, -1));
        jPanel1.add(jTextFieldItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 10, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (jTextFieldName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter item name");
            jTextFieldName.requestFocus();
        } else if (jComboBoxCategory.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Select category");
            jComboBoxCategory.requestFocus();
        } else {
            FoodItem localFoodItem = new FoodItem();
            Category category = new Category();
            FoodItemsDao foodItemsDao = new FoodItemsDao();
            
            
            if (this.formAction.equals("add") || this.formAction.equals("edit")) {
                localFoodItem.setItemName(jTextFieldName.getText().trim());
                localFoodItem.setDescription(jTextAreaDescription.getText().trim());
                localFoodItem.setImage(jTextField2.getText().trim());
                category.setId(Integer.valueOf(jComboBoxCategoryId.getSelectedItem().toString()));
                localFoodItem.setCategory(category);
                if(this.formAction.equals("add")) {
                    foodItemsDao.add(localFoodItem);
                } else {
                    localFoodItem.setItemId(Integer.valueOf(jTextFieldItemId.getText()));
                    foodItemsDao.editDelete(localFoodItem, this.formAction);
                }
            }
            clearData();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jComboBoxCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCategoryItemStateChanged
        jComboBoxCategoryId.setSelectedIndex(jComboBoxCategory.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxCategoryItemStateChanged
    
    private void getCategory() {
        CategoryDao categoryDao = new CategoryDao();
        for(Category category : categoryDao.getMenusData("")) {
            jComboBoxCategory.addItem(category.getName());
            jComboBoxCategoryId.addItem(category.getId());
        }
    }
    
    private void clearData() {
        jTextAreaDescription.setText("");
        jTextField2.setText("");
        jTextFieldName.setText("");
        jComboBoxCategory.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxCategory;
    private javax.swing.JComboBox jComboBoxCategoryId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldItemId;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
