/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tgif.view;

import com.tgif.apps.Main;
import com.tgif.dao.CategoryDao;
import com.tgif.dao.HeaderDetailOrderDao;
import com.tgif.model.Category;
import com.tgif.model.OrderDetail;
import com.tgif.util.TableManager;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.xswingx.PromptSupport;

/**
 *
 * @author JPlans
 */
public class FormDetailOrderManagement extends javax.swing.JInternalFrame {

    private String[] header = {"ID", "Table Number", "Item Name", "Serving", "Sauce/s", "Side Dish", "Quantity"};
    private boolean[] cellEditable = {false, false, false, false, false, false, false};
    private int[] width = {80, 150, 200, 200, 250, 200, 100};

    /**
     * Creates new form FormSupplierManagement
     */
    public FormDetailOrderManagement() {
        initComponents();
        initTextField();
        initTable();
        jLabelSpinner.setVisible(false);
        jButtonNew.setVisible(false);
    }

    private void initTextField() {
        PromptSupport.setPrompt("Search", jTextFieldSearch);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, jTextFieldSearch);
        PromptSupport.setForeground(Color.LIGHT_GRAY, jTextFieldSearch);
    }

    private void initTable() {
        TableManager.setModel(jXTableSuppliers, jScrollPaneSuppliers, null, header, false, false, 0, cellEditable, width);
        getMenus();
    }

    private void getMenus() {
        TableManager.getTableModel(jXTableSuppliers).setRowCount(0);
        HeaderDetailOrderDao dao = new HeaderDetailOrderDao();
        List<OrderDetail> od = dao.getDetailOrders();
        String sauce="";
        for(int i = 0; i < od.size(); i++){
            for (int j = 0; j < od.get(i).getSauces().size(); j++) {
                sauce += od.get(j).getSauces() + ", ";
            }
            TableManager.getTableModel(jXTableSuppliers).addRow(new Object[]{
                od.get(i).getId(),
                od.get(i).getTableNumber(),
                od.get(i).getFoodItem().getItemName(),
                od.get(i).getServing().getServingName(),
                od.get(i).getSideDish().getSideDishName(),
                sauce,
                od.get(i).getQty()
            });
        }
        
//        for() {
//            TableManager.getTableModel(jXTableSuppliers).addRow(new Object[]{
//                od.getId(),
//                od.getTableNumber(),
//                od.getFoodItem().getItemName(),
//                od.getServing().getServingName(),
//                od.getSideDish().getSideDishName(),
//                sauce,
//                od.getQty()
//            });
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jScrollPaneSuppliers = new javax.swing.JScrollPane();
        jXTableSuppliers = new org.jdesktop.swingx.JXTable();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabelSpinner = new javax.swing.JLabel();

        setTitle("Detail Order Management");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 90, -1));

        jButtonNew.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonNew.setText("New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 450, -1));

        jScrollPaneSuppliers.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jXTableSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPaneSuppliers.setViewportView(jXTableSuppliers);

        jPanel1.add(jScrollPaneSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 650, 310));

        jTextFieldSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 540, 23));

        jButtonSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonSearch.setText("Search...");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 100, -1));

        jLabelSpinner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tgif/icons/loading_icon_2_rev01.gif"))); // NOI18N
        jPanel1.add(jLabelSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonSearch.doClick();
        }
    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed

        getMenus();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        FormCategory form = new FormCategory(Main.JFParent, true);
        form.setTitle("Add Category");
        form.setLocationRelativeTo(Main.JFParent);
        form.setVisible(true);
        jButtonSearch.doClick();
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelSpinner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneSuppliers;
    private javax.swing.JTextField jTextFieldSearch;
    private org.jdesktop.swingx.JXTable jXTableSuppliers;
    // End of variables declaration//GEN-END:variables
}
