/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tgif.view;

import com.tgif.apps.Main;
import com.tgif.dao.FeedbackDao;
import com.tgif.model.Feedback;
import com.tgif.util.TableManager;

/**
 *
 * @author Mon
 */
public class FormFeedback extends javax.swing.JInternalFrame {
    private String[] header = {"ID", "Customer Name", "Message"};
    private boolean[] cellEditable = {false, false, false};
    private int[] width = {50, 150, 405};
    /**
     * Creates new form FormFeedback
     */
    public FormFeedback() {
        initComponents();
        initTable();
    }
    private void initTable() {
        TableManager.setModel(jTable1, jScrollPane1, null, header, false, false, 0, cellEditable, width);
        getFeedback();
    }
    
    private void getFeedback() {
        TableManager.getTableModel(jTable1).setRowCount(0);
        FeedbackDao fd = new FeedbackDao();
        for (Feedback feedback : fd.getFeedbacks()) {
            TableManager.getTableModel(jTable1).addRow(new Object[]{
                feedback.getId(),
                feedback.getCustomerName(),
                feedback.getMessage()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setMaximizable(true);
        setResizable(true);
        setTitle("Feedback");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 340));

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cName = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String message = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        com.tgif.view.Feedback f = new com.tgif.view.Feedback(null, true);
        f.setMsg(message);
        f.setcName(cName);
        f.setLocationRelativeTo(Main.JFParent);
        f.setVisible(true);
        getFeedback();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
