/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tgif.view;

import com.tgif.apps.Main;
import com.tgif.dao.CategoryDao;
import com.tgif.model.Category;
import com.tgif.util.TableManager;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import org.jdesktop.xswingx.PromptSupport;

/**
 *
 * @author JPlans
 */
public class FormCategoryManagement extends javax.swing.JInternalFrame {

    private String[] header = {"ID", "Category Name", "Items"};
    private boolean[] cellEditable = {false, false, false};
    private int[] width = {90, 250, 90};

    /**
     * Creates new form FormSupplierManagement
     */
    public FormCategoryManagement() {
        initComponents();
        initTextField();
        initTable();
        jLabelSpinner.setVisible(false);
    }

    private void initTextField() {
        PromptSupport.setPrompt("Search", jTextFieldSearch);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, jTextFieldSearch);
        PromptSupport.setForeground(Color.LIGHT_GRAY, jTextFieldSearch);
    }

    private void initTable() {
        TableManager.setModel(jXTableSuppliers, jScrollPaneSuppliers, null, header, false, false, 0, cellEditable, width);
        getMenus("");
    }

    private void getMenus(String param) {
        TableManager.getTableModel(jXTableSuppliers).setRowCount(0);
        CategoryDao categoryDao = new CategoryDao();
        for (Category category : categoryDao.getMenusData(param)) {
            TableManager.getTableModel(jXTableSuppliers).addRow(new Object[]{
                category.getId(),
                category.getName(),
                category.getItemsCount()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPaneSuppliers = new javax.swing.JScrollPane();
        jXTableSuppliers = new org.jdesktop.swingx.JXTable();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabelSpinner = new javax.swing.JLabel();

        setTitle("Category Management");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 90, -1));

        jButtonNew.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonNew.setText("New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 90, -1));

        jButtonEdit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 90, -1));

        jButtonDelete.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 450, -1));

        jScrollPaneSuppliers.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jXTableSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneSuppliers.setViewportView(jXTableSuppliers);

        jPanel1.add(jScrollPaneSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 450, 310));

        jTextFieldSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 23));

        jButtonSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonSearch.setText("Search...");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 100, -1));

        jLabelSpinner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tgif/icons/loading_icon_2_rev01.gif"))); // NOI18N
        jPanel1.add(jLabelSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonSearch.doClick();
        }
    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed

        getMenus(jTextFieldSearch.getText());
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        FormCategory form = new FormCategory(Main.JFParent, true);
        form.setTitle("Add Category");
        form.setLocationRelativeTo(Main.JFParent);
        form.setVisible(true);
        jButtonSearch.doClick();
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        if (jXTableSuppliers.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Select record to edit");
            return;
        }
        
        Category category = new Category();
        String label = TableManager.getTableModel(jXTableSuppliers).getValueAt(jXTableSuppliers.getSelectedRow(), 1).toString();
        category.setName(label);
        int id = Integer.valueOf(TableManager.getTableModel(jXTableSuppliers).getValueAt(jXTableSuppliers.getSelectedRow(), 0).toString());
        category.setId(id);
        
        FormCategory form = new FormCategory(Main.JFParent, true);
        form.setTitle("Edit Category");
        form.setLocationRelativeTo(Main.JFParent);
        form.setCategory(category);
        form.setData();
        form.setVisible(true);
        jButtonSearch.doClick();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if (jXTableSuppliers.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Select record to edit");
            return;
        }
        int id = Integer.valueOf(TableManager.getTableModel(jXTableSuppliers).getValueAt(jXTableSuppliers.getSelectedRow(), 0).toString());
        Category category = new Category();
        String label = TableManager.getTableModel(jXTableSuppliers).getValueAt(jXTableSuppliers.getSelectedRow(), 1).toString();
        category.setName(label);
        category.setId(id);
        CategoryDao categoryDao = new CategoryDao();
        categoryDao.save(category, "delete");
        jButtonSearch.doClick();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelSpinner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneSuppliers;
    private javax.swing.JTextField jTextFieldSearch;
    private org.jdesktop.swingx.JXTable jXTableSuppliers;
    // End of variables declaration//GEN-END:variables
}
