/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tgif.view;

import com.tgif.dao.MembershipDAO;
import com.tgif.model.Membership;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Mon
 */
public class FormMemberShip extends javax.swing.JDialog {

    /**
     * Creates new form FormMemberShip
     */
    private String formAction = "add";
    private List<String> memberShipId;
    private Membership membership;

    public void setMemberShipId(List<String> memberShipId) {
        this.memberShipId = memberShipId;
    }

    public void setMembership(Membership membership) {
        this.membership = membership;
    }

    public FormMemberShip(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setData() {
        if (this.membership != null) {
            jTextFieldMembershipId.setEnabled(false);
            jTextFieldMembershipId.setText(this.membership.getMemberId());
            jTextFieldName.setText(this.membership.getName());
            jTextAreaAddress.setText(this.membership.getAddress());
            jTextFieldContactNum.setText(this.membership.getContactNumber());
            if (this.membership.getStatus().equalsIgnoreCase("I")) {
                jRadioButtonInactive.setSelected(true);
            } else {
                jRadioButtonActive.setSelected(true);
            }
            this.formAction = "edit";
        } else {
            System.out.println("null");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMembershipId = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jTextFieldContactNum = new javax.swing.JTextField();
        jRadioButtonActive = new javax.swing.JRadioButton();
        jRadioButtonInactive = new javax.swing.JRadioButton();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Membership ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Member Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Address:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Contact Num:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Membership Status:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, 30));

        jTextFieldMembershipId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextFieldMembershipId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 250, 30));

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 250, 30));

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 250, 60));

        jTextFieldContactNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldContactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactNumActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldContactNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 250, 30));

        buttonGroup1.add(jRadioButtonActive);
        jRadioButtonActive.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonActive.setText("Active");
        jPanel1.add(jRadioButtonActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, 30));

        buttonGroup1.add(jRadioButtonInactive);
        jRadioButtonInactive.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonInactive.setText("Inactive");
        jPanel1.add(jRadioButtonInactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, 30));

        jButtonSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 80, -1));

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldContactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactNumActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (this.memberShipId.contains(jTextFieldMembershipId.getText())) {
            JOptionPane.showMessageDialog(this, "Membership ID already exist");
            return;
        }

        if (jTextFieldMembershipId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter membership ID");
            jTextFieldMembershipId.requestFocus();
        } else if (jTextFieldName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter name");
            jTextFieldName.requestFocus();
        } else if (jTextAreaAddress.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter address");
            jTextAreaAddress.requestFocus();
        } else if (jTextFieldContactNum.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter contact number");
            jTextFieldContactNum.requestFocus();
        } else if (jRadioButtonActive.isSelected() == false && jRadioButtonInactive.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Select if active or not");
        } else {

            MembershipDAO mdao = new MembershipDAO();
            Membership m = new Membership();

            m.setMemberId(jTextFieldMembershipId.getText());
            m.setName(jTextFieldName.getText());
            m.setAddress(jTextAreaAddress.getText());
            m.setContactNumber(jTextFieldContactNum.getText());
            if (jRadioButtonActive.isSelected()) {
                m.setStatus("A");
            } else {
                m.setStatus("I");
            }
            mdao.save(m, this.formAction);
            clearData();
            dispose();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    private void clearData() {
        jTextAreaAddress.setText("");
        jTextFieldContactNum.setText("");
        jTextFieldMembershipId.setText("");
        jTextFieldName.setText("");
        jRadioButtonActive.setSelected(false);
        jRadioButtonInactive.setSelected(false);
        jTextFieldMembershipId.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonActive;
    private javax.swing.JRadioButton jRadioButtonInactive;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldContactNum;
    private javax.swing.JTextField jTextFieldMembershipId;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
