/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tgif.view;

import com.tgif.connection.DBConnection;
import com.tgif.dao.CashierDao;
import com.tgif.model.TransactionDetail;
import com.tgif.model.TransactionHeader;
import com.tgif.util.TableManager;
import java.awt.Font;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mon
 */
public class FormTransactionDetail extends javax.swing.JDialog {
//    private String transactionId;

    private String[] header = {"Detail", "price", "quantity"};
    private boolean[] cellEditable = {false, false, false};
    private int[] width = {578, 100, 100};
    JasperReport jasperReport;
    JasperPrint jasperPrint;
    /**
     * Creates new form FormTransactionDetail
     */
    public FormTransactionDetail(java.awt.Frame parent, boolean modal, int tableNumber) {
        super(parent, modal);
        initComponents();
        this.setTitle("Table " + tableNumber + " Order Details");
        jLabelTableNumber.setText(String.valueOf(tableNumber));
        jButtonCheckOut.requestFocus();
        initTable();
    }

    private void initTable() {
        TableManager.setModel(jTableTransactionDetails, jScrollPane1, null, header, false, false, 0, cellEditable, width);
        jTableTransactionDetails.setFont(new Font("Tahoma", Font.PLAIN, 16));
        jTableTransactionDetails.setRowHeight(jTableTransactionDetails.getRowHeight() * 2);
        getTransactionDetails();
    }

    private void getTransactionDetails() {
        Double credit = 0.0;
        Double cash = 0.0;
        CashierDao cashierDao = new CashierDao();
        TableManager.getTableModel(jTableTransactionDetails).setRowCount(0);
        for (TransactionDetail detail : cashierDao.getTransactionDetails(Integer.valueOf(jLabelTableNumber.getText()))) {
            System.out.println("here");
            jTextFieldTransactionId.setText(detail.getTransactionId());
            String sauce = "";
            credit = detail.getCredit();
            cash = detail.getCash();
            for (int i = 0; i < detail.getSauce().size(); i++) {
                sauce = detail.getSauce().get(i).getAbbreviation() + ", ";
            }
            String sauces="";
            if (!sauce.isEmpty()) {
                sauces = sauce.substring(0, sauce.length() - 2);
            }
            String details = detail.getFoodItem().getItemName() + ", Serving: (" + detail.getServing().getAbbreviation() + "), "
                    + "Sauce/s: (" + sauces + "), Side Dish: (" + detail.getSideDish().getAbbreviation() + ")";
            TableManager.getTableModel(jTableTransactionDetails).addRow(new Object[]{
                details,
                detail.getPrice(),
                detail.getQuantity()
            });
        }
        jLabelCash.setText(String.valueOf(cash));
        jLabelTotal.setText(String.valueOf(credit));
        Double change = cash - credit;
        jLabelChange.setText(String.valueOf(change));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTransactionDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelChange = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCash = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jButtonCheckOut = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelTableNumber = new javax.swing.JLabel();
        jTextFieldTransactionId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableTransactionDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableTransactionDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 780, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cash Amount:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabelChange.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelChange.setText("0.00");
        jPanel1.add(jLabelChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Change:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabelCash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCash.setText("0.00");
        jPanel1.add(jLabelCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTotal.setText("0.00");
        jPanel1.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jButtonCheckOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCheckOut.setText("Check Out");
        jButtonCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckOutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, 60));

        jButtonClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 110, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Table Number:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelTableNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTableNumber.setText("0");
        jPanel1.add(jLabelTableNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel1.add(jTextFieldTransactionId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckOutActionPerformed
        CashierDao cashierDao = new CashierDao();
        int result = JOptionPane.showConfirmDialog(this, "Check Out", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.NO_OPTION) {
//            JOptionPane.showMessageDialog(this, "Cancel");
            return;
        }
        printReport();
        TransactionHeader transactionHeader = new TransactionHeader();
        transactionHeader.setTransactionId(jTextFieldTransactionId.getText());
        transactionHeader.setCashAmount(Double.valueOf(jLabelCash.getText()));
        transactionHeader.setTableNumber(Integer.valueOf(jLabelTableNumber.getText()));
        transactionHeader.setCashierId("cashier1"); // username = id
        if (!transactionHeader.getTransactionId().equalsIgnoreCase("")) {
            cashierDao.save(transactionHeader);
            this.dispose();
        } else {
            System.out.println("transaction_header: "+transactionHeader);
            System.out.println("null");
        }
    }//GEN-LAST:event_jButtonCheckOutActionPerformed
     private void printReport() {

        try {

            HashMap map = new HashMap();

      
            map.put("transaction_id", jTextFieldTransactionId.getText().trim());
            
            System.out.println(map);
            String path = "/report/tgif_recipe.jasper";

            print(map, path);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void print(HashMap params, String reportPath){
        try {
             // System.out.println(params);
                    //JasperReport jasperReport = (JasperReport)JRLoader.loadObject(getClass().getResource("/sample_report/sample_print.jasper"));
                   jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResource(reportPath));
                              
                   // JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params , db.connect());
                   DBConnection db = new DBConnection();
                   jasperPrint = JasperFillManager.fillReport(jasperReport, params, db.connect());
                   JasperViewer.viewReport(jasperPrint, false);
        }
        catch (Exception e) {
//            MessageDialog.show(CustomerService.JFParent, e);
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckOut;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCash;
    private javax.swing.JLabel jLabelChange;
    private javax.swing.JLabel jLabelTableNumber;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTransactionDetails;
    private javax.swing.JTextField jTextFieldTransactionId;
    // End of variables declaration//GEN-END:variables
}
